# change the followings to match your Github username and repo name
baseurl: "/tailpages" # the name of your github repo
url: "https://WenhanZheng.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Vanessa & Amanda's website"
description: This is the website for Vanessa and Amanda

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Vanessa & Amanda
author-bio: Students  # change to false to hide
author-image: WechatIMG16539.jpeg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Skills
  permalink: skills
- text: Blog
  permalink: blog
- text: Project
  permalink: project

# use false to turn off any social media links
twitter: https://twitter.com/home
facebook: https://www.facebook.com/profile.php?id=100087379552608
instagram: https://www.instagram.com/vanessahu021114/
github: https://github.com/Vanessa021114
linkedin: https://www.linkedin.cn/incareer/in/ACoAAD8XATwBq0G_oegnz7r7SBPxx2-rqi7ixQU
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
